#!/bin/bash

# Script to set up Supabase Function environment variables from .env file
# This creates a local .env file for Edge Functions (LOCAL development only)
# Usage: ./scripts/setup-secrets.sh

if [ ! -f .env ]; then
  echo "❌ ERROR: .env file not found"
  echo ""
  echo "Please create a .env file with your secrets first."
  exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Setting up Supabase Function environment variables (LOCAL ONLY)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Note: This creates supabase/functions/.env for local development only."
echo "Production secrets must be set separately via Supabase Dashboard."
echo ""

# Create supabase/functions directory if it doesn't exist
mkdir -p supabase/functions

# Read ANTHROPIC_API_KEY from root .env
ANTHROPIC_API_KEY=$(grep "^ANTHROPIC_API_KEY=" .env | cut -d= -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -d '"' | tr -d "'")

# Read RATE_LIMIT_MAX_REQUESTS from root .env (optional)
RATE_LIMIT_MAX_REQUESTS=$(grep "^RATE_LIMIT_MAX_REQUESTS=" .env | cut -d= -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr -d '"' | tr -d "'")

# Create or update supabase/functions/.env
FUNCTIONS_ENV_FILE="supabase/functions/.env"

echo "# Environment variables for Supabase Edge Functions (local development only)" > "$FUNCTIONS_ENV_FILE"
echo "# This file is automatically generated by scripts/setup-secrets.sh" >> "$FUNCTIONS_ENV_FILE"
echo "# Do not commit this file to version control" >> "$FUNCTIONS_ENV_FILE"
echo "" >> "$FUNCTIONS_ENV_FILE"

if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "⚠ WARNING: ANTHROPIC_API_KEY not found in .env"
  echo "Skipping ANTHROPIC_API_KEY..."
else
  echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> "$FUNCTIONS_ENV_FILE"
  echo "✓ ANTHROPIC_API_KEY added to $FUNCTIONS_ENV_FILE"
fi

if [ -z "$RATE_LIMIT_MAX_REQUESTS" ]; then
  echo "RATE_LIMIT_MAX_REQUESTS not found in .env (using default: 10)"
  echo "RATE_LIMIT_MAX_REQUESTS=10" >> "$FUNCTIONS_ENV_FILE"
else
  echo "RATE_LIMIT_MAX_REQUESTS=$RATE_LIMIT_MAX_REQUESTS" >> "$FUNCTIONS_ENV_FILE"
  echo "✓ RATE_LIMIT_MAX_REQUESTS added to $FUNCTIONS_ENV_FILE"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Done! Environment variables are now available to LOCAL Supabase Functions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The file $FUNCTIONS_ENV_FILE has been created/updated."
echo "Supabase will automatically load these when running functions locally."
echo ""
echo "Note: These environment variables only apply to your local Supabase instance."
echo "For production, set secrets via: Supabase Dashboard > Project Settings > Edge Functions"
